import { Tag, Group, Task } from './types'

export const mockTags: Tag[] = [
  { id: 't1', name: 'Design', color: '#6C5CE7' },
  { id: 't2', name: 'Frontend', color: '#00B894' },
  { id: 't3', name: 'Backend', color: '#E17055' },
  { id: 't4', name: 'Urgent', color: '#FF6B6B' },
  { id: 't5', name: 'Research', color: '#FDCB6E' },
  { id: 't6', name: 'Bug', color: '#D63031' },
  { id: 't7', name: 'Feature', color: '#0984E3' },
  { id: 't8', name: 'Meeting', color: '#A29BFE' },
]

export const mockGroups: Group[] = [
  { id: 'g1', name: 'Product Launch', icon: '🚀', color: '#6C5CE7', sortOrder: 0 },
  { id: 'g2', name: 'Sales Pipeline', icon: '💰', color: '#00B894', sortOrder: 1 },
  { id: 'g3', name: 'Engineering', icon: '⚙️', color: '#E17055', sortOrder: 2 },
  { id: 'g4', name: 'Marketing', icon: '📣', color: '#FDCB6E', sortOrder: 3 },
  { id: 'g5', name: 'Personal', icon: '🏠', color: '#74B9FF', sortOrder: 4 },
]

const today = new Date()
const tomorrow = new Date(today); tomorrow.setDate(today.getDate() + 1)
const nextWeek = new Date(today); nextWeek.setDate(today.getDate() + 5)
const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1)
const inTwoDays = new Date(today); inTwoDays.setDate(today.getDate() + 2)

function d(date: Date) { return date.toISOString().split('T')[0] }

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Finalize landing page copy',
    description: 'Review and finalize all the copy for the new landing page. Ensure messaging aligns with brand guidelines and resonates with target audience.',
    status: 'in_progress',
    priority: 'high',
    dueDate: d(today),
    assignee: 'Sarah Chen',
    customer: 'Acme Corp',
    groupId: 'g1',
    parentId: null,
    tags: [mockTags[0], mockTags[1]],
    subtasks: [
      {
        id: '1a', title: 'Write hero section copy', description: '', status: 'done', priority: 'high',
        dueDate: null, assignee: 'Sarah Chen', customer: '', groupId: 'g1', parentId: '1', tags: [], subtasks: [],
        completedAt: d(yesterday), createdAt: d(yesterday), updatedAt: d(yesterday),
      },
      {
        id: '1b', title: 'Draft feature descriptions', description: '', status: 'todo', priority: 'medium',
        dueDate: d(tomorrow), assignee: 'Sarah Chen', customer: '', groupId: 'g1', parentId: '1', tags: [], subtasks: [],
        completedAt: null, createdAt: d(yesterday), updatedAt: d(yesterday),
      },
    ],
    completedAt: null,
    createdAt: '2026-03-15',
    updatedAt: d(today),
  },
  {
    id: '2',
    title: 'Review Q1 sales metrics',
    description: 'Compile and analyze Q1 sales data for the quarterly review presentation.',
    status: 'todo',
    priority: 'urgent',
    dueDate: d(today),
    assignee: 'Marcus Rivera',
    customer: 'Globex',
    groupId: 'g2',
    parentId: null,
    tags: [mockTags[4], mockTags[7]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-14',
    updatedAt: d(today),
  },
  {
    id: '3',
    title: 'Fix authentication timeout bug',
    description: 'Users are being logged out after 5 minutes instead of the configured 30 minute session timeout.',
    status: 'in_progress',
    priority: 'urgent',
    dueDate: d(tomorrow),
    assignee: 'Alex Kim',
    customer: '',
    groupId: 'g3',
    parentId: null,
    tags: [mockTags[2], mockTags[5]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-17',
    updatedAt: d(today),
  },
  {
    id: '4',
    title: 'Design email campaign template',
    description: 'Create a reusable email template for the upcoming spring campaign.',
    status: 'todo',
    priority: 'medium',
    dueDate: d(inTwoDays),
    assignee: 'Jordan Lee',
    customer: 'Initech',
    groupId: 'g4',
    parentId: null,
    tags: [mockTags[0], mockTags[6]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-16',
    updatedAt: d(today),
  },
  {
    id: '5',
    title: 'Prepare investor deck updates',
    description: 'Update the investor presentation with latest metrics, roadmap changes, and customer testimonials.',
    status: 'todo',
    priority: 'high',
    dueDate: d(nextWeek),
    assignee: 'Sarah Chen',
    customer: '',
    groupId: 'g1',
    parentId: null,
    tags: [mockTags[0], mockTags[7]],
    subtasks: [
      {
        id: '5a', title: 'Update financial projections', description: '', status: 'todo', priority: 'high',
        dueDate: d(inTwoDays), assignee: 'Sarah Chen', customer: '', groupId: 'g1', parentId: '5', tags: [], subtasks: [],
        completedAt: null, createdAt: d(today), updatedAt: d(today),
      },
      {
        id: '5b', title: 'Add new customer logos', description: '', status: 'todo', priority: 'low',
        dueDate: null, assignee: 'Jordan Lee', customer: '', groupId: 'g1', parentId: '5', tags: [], subtasks: [],
        completedAt: null, createdAt: d(today), updatedAt: d(today),
      },
      {
        id: '5c', title: 'Review competitive landscape slide', description: '', status: 'done', priority: 'medium',
        dueDate: null, assignee: 'Marcus Rivera', customer: '', groupId: 'g1', parentId: '5', tags: [], subtasks: [],
        completedAt: d(yesterday), createdAt: '2026-03-15', updatedAt: d(yesterday),
      },
    ],
    completedAt: null,
    createdAt: '2026-03-12',
    updatedAt: d(today),
  },
  {
    id: '6',
    title: 'Set up CI/CD pipeline for mobile app',
    description: 'Configure GitHub Actions for automated testing and deployment of the mobile application.',
    status: 'todo',
    priority: 'medium',
    dueDate: d(nextWeek),
    assignee: 'Alex Kim',
    customer: '',
    groupId: 'g3',
    parentId: null,
    tags: [mockTags[2], mockTags[6]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-16',
    updatedAt: d(today),
  },
  {
    id: '7',
    title: 'Client onboarding call with Acme Corp',
    description: 'Initial onboarding call to set up their account and walk through the platform features.',
    status: 'todo',
    priority: 'high',
    dueDate: d(tomorrow),
    assignee: 'Marcus Rivera',
    customer: 'Acme Corp',
    groupId: 'g2',
    parentId: null,
    tags: [mockTags[7]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-18',
    updatedAt: d(today),
  },
  {
    id: '8',
    title: 'Write API documentation for v2 endpoints',
    description: 'Document all new v2 API endpoints with examples, request/response schemas, and error codes.',
    status: 'in_progress',
    priority: 'medium',
    dueDate: d(nextWeek),
    assignee: 'Alex Kim',
    customer: '',
    groupId: 'g3',
    parentId: null,
    tags: [mockTags[2], mockTags[6]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-14',
    updatedAt: d(today),
  },
  {
    id: '9',
    title: 'Groceries for the week',
    description: '',
    status: 'todo',
    priority: 'low',
    dueDate: d(tomorrow),
    assignee: '',
    customer: '',
    groupId: 'g5',
    parentId: null,
    tags: [],
    subtasks: [],
    completedAt: null,
    createdAt: d(today),
    updatedAt: d(today),
  },
  {
    id: '10',
    title: 'Research competitor pricing models',
    description: 'Analyze pricing strategies of top 5 competitors and prepare a comparison matrix.',
    status: 'done',
    priority: 'medium',
    dueDate: d(yesterday),
    assignee: 'Jordan Lee',
    customer: 'Globex',
    groupId: 'g2',
    parentId: null,
    tags: [mockTags[4]],
    subtasks: [],
    completedAt: d(yesterday),
    createdAt: '2026-03-10',
    updatedAt: d(yesterday),
  },
  {
    id: '11',
    title: 'Plan team offsite agenda',
    description: 'Organize the agenda for the upcoming team offsite including activities and workshops.',
    status: 'todo',
    priority: 'low',
    dueDate: null,
    assignee: 'Sarah Chen',
    customer: '',
    groupId: null,
    parentId: null,
    tags: [mockTags[7]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-17',
    updatedAt: d(today),
  },
  {
    id: '12',
    title: 'Social media content calendar — April',
    description: 'Plan and schedule all social media posts for April across LinkedIn, Twitter, and Instagram.',
    status: 'todo',
    priority: 'medium',
    dueDate: d(nextWeek),
    assignee: 'Jordan Lee',
    customer: 'Initech',
    groupId: 'g4',
    parentId: null,
    tags: [mockTags[0], mockTags[6]],
    subtasks: [],
    completedAt: null,
    createdAt: '2026-03-18',
    updatedAt: d(today),
  },
]
